openapi: 3.0.3
info:
  title: 食事分析API (Meal Analysis API)
  version: v1
  description: 食事の画像とテキストを分析し、料理と材料を特定するAPI。
servers:
  - url: http://localhost:8000/api
    description: ローカル開発サーバー
paths:
  /v1/meal-analyses:
    post:
      summary: 食事画像の分析
      operationId: analyzeMealImage
      description: >
        食事画像（およびオプションのテキスト）を送信して分析を依頼します。
        特定された料理、種類、量、材料を含む構造化JSONを返します。
      tags:
        - Meal Analysis
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                image:
                  type: string
                  format: binary
                  description: 食事の画像ファイル。
                text:
                  type: string
                  nullable: true
                  description: 食事に関するオプションのテキスト記述やメモ。
              required:
                - image
      responses:
        '200':
          description: 食事分析成功。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MealAnalysisResponseObject'
        '400':
          description: 不正なリクエスト - 無効な入力が提供されました。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: 内部サーバーエラー。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    IngredientObject:
      type: object
      description: 材料オブジェクト
      properties:
        ingredient_name:
          type: string
          description: 材料の名称。
          example: "鶏むね肉"
        weight_g:
          type: number
          format: float
          description: 材料の推定重量（グラム単位）。
          example: 150.5
      required:
        - ingredient_name
        - weight_g
    DishObject:
      type: object
      description: 料理オブジェクト
      properties:
        dish_name:
          type: string
          description: 特定された料理の名称。
          example: "鶏肉のグリル"
        type:
          type: string
          description: 料理の種類（例: 主菜, 副菜, スープ, デザート）。
          example: "主菜"
        quantity_on_plate:
          type: string
          description: 皿の上に載っている料理のおおよその量や個数。
          example: "1切れ"
        ingredients:
          type: array
          description: この料理に含まれる材料のリスト。
          items:
            $ref: '#/components/schemas/IngredientObject'
      required:
        - dish_name
        - type
        - quantity_on_plate
        - ingredients
    MealAnalysisResponseObject:
      type: object
      description: 食事分析レスポンス
      properties:
        dishes:
          type: array
          description: 画像から特定された料理のリスト。
          items:
            $ref: '#/components/schemas/DishObject'
      required:
        - dishes
    ErrorResponse:
      type: object
      description: エラーレスポンス
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              description: エラーコード
              example: "INVALID_IMAGE_FORMAT"
            message:
              type: string
              description: エラーメッセージ
              example: "アップロードされたファイルはサポートされている画像形式ではありません。"
          required:
            - code
            - message
      required:
        - error 