#!/usr/bin/env python3
import asyncio
import sys
import os
sys.path.append(os.getcwd())
from app.services.usda_service import USDAService

async def test_penne_queries():
    usda_service = USDAService()
    
    # Test the queries that were generated by Phase 1
    test_queries = [
        "Penne pasta, cooked",      # Phase1生成クエリ1
        "Pasta, penne, cooked",     # Phase1生成クエリ2
        "Penne pasta",              # シンプル版
        "Pasta, penne",             # シンプル版（語順違い）
        "Penne",                    # 最もシンプル
        "Pasta, cooked",            # 汎用的
        "Pasta"                     # 超汎用的
    ]
    
    for query in test_queries:
        print(f'=== Testing: "{query}" ===')
        try:
            results = await usda_service.search_foods_rich(
                query=query,
                page_size=10,
                data_types=['Foundation', 'SR Legacy', 'FNDDS', 'Branded']
            )
            
            print(f'Found {len(results)} results:')
            for i, result in enumerate(results):
                print(f'{i+1}. FDC ID: {result.fdc_id}, Description: {result.description}')
                print(f'   Type: {result.data_type}, Score: {result.score}')
            print()
        except Exception as e:
            print(f'ERROR: {e}')
            print()

if __name__ == '__main__':
    asyncio.run(test_penne_queries()) 